accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/',SignUpView.as_view(),name='signup'),
]

articles/urls.py
from django.urls import path
from .views import *



urlpatterns = [
    path('', ArticleListView.as_view(), name='article_list'),
    path('new', ArticleCreateView.as_view(), name='article_new'),
    path('<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('<int:pk>/edit/', ArticleUpdateView.as_view(), name='article_edit'),
    path('<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('',include('pages.urls')),
    path('',include('articles.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)





pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path('home',HomePageView.as_view(),name='home'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)
    linkedin = models.CharField(max_length=100, null=True,blank=True,default='')


articles/models.py
from django.contrib.auth import get_user_model
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=150,default='')
    summary = models.CharField(max_length=500, blank=True)
    body = RichTextField()
    picture = models.ImageField(upload_to='images/', blank=True)
    date = models.DateField(auto_now_add=True)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    # def get_absolute_url(self):
    #     return reverse('article_detail', args=[str(self.id)])

class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    content = models.TextField()
    post = models.ForeignKey(Article, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {}'.format(self.name)

pages/models.py
# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from .models import CustomUser



class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'age', 'linkedin']


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name', 'email', 'age', 'linkedin']



articles/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'content')

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomUserCreationForm

# Create your views here.

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'



articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView
from django.views.generic import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .models import Article, Comment
from .forms import CommentForm
from django.shortcuts import get_object_or_404



# Create your views here.


class ArticleListView(ListView):
    model = Article
    template_name = 'article_list.html'



class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = 'article_new.html'
    fields = ['title','picture','body','summary']
    success_url = reverse_lazy('article_list')


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)




class ArticleUpdateView(LoginRequiredMixin,UserPassesTestMixin, UpdateView):
    model = Article
    template_name = 'article_edit.html'
    fields = ['title', 'summary', 'body', 'picture']
    success_url = reverse_lazy('article_list')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class ArticleDetailView( DetailView):
    model = Article
    template_name = 'article_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs["pk"]
        # slug = self.kwargs["slug"]

        form = CommentForm()
        post = get_object_or_404(Article, pk=pk)
        comments = post.comment_set.all()

        context['post'] = post
        context['comments'] = comments
        context['form'] = form
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        self.object = self.get_object()
        context = super().get_context_data(**kwargs)

        post = Article.objects.filter(id=self.kwargs['pk'])[0]
        comments = post.comment_set.all()

        context['post'] = post
        context['comments'] = comments
        context['form'] = form

        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            content = form.cleaned_data['content']

            comment = Comment.objects.create(
                name=name, email=email, content=content, post=post
            )

            form = CommentForm()
            context['form'] = form
            return self.render_to_response(context=context)

        return self.render_to_response(context=context)



class ArticleDeleteView(LoginRequiredMixin,UserPassesTestMixin, DeleteView):
    model = Article
    template_name = 'article_delete.html'
    success_url = reverse_lazy('article_list')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

pages/views.py
from django.views.generic.base import TemplateView

# Create your views here.

class HomePageView(TemplateView):
    template_name = 'home.html'

templates/article_delete.html
{% extends 'base.html' %}

 {% block content %}
<form action="" method="post" >
     {% csrf_token %}
     <h3>{{ article.title }}</h3>
     <p>Are you sure delete this post?</p>
<button type="submit" class="btn btn-danger">Submit</button>
    <a class="btn btn-outline-primary" href="{% url 'home' %}" role="button">Home</a>
 </form>
{% endblock content %}

templates/article_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="card" >
          <div class="card-body">
              {%  if object.picture %}
                <img class="card-img-top" src="{{ object.picture.url }}" alt="{{ object.title }}" width="900px" height="750px">
              {% endif %}
              <h1 class="card-title">{{ object.title }}</h1>
              <h6 class="card-subtitle mb-2 text-muted">Muallif: {{ object.author }} | {{ object.date }}</h6>
              <p class="card-text">{{ object.body | safe }}</p>
              {% if user.is_authenticated and object.author.id == user.id %}
              <a href="{% url 'article_edit' object.id %}" role="button" class="btn btn-outline-primary">Edit</a> |
              <a href="{% url 'article_delete' object.id %}" role="button" class="btn btn-outline-primary">Delete</a> |
              <a href="{% url 'article_list' %}" role="button" class="btn btn-outline-primary">All News</a>
              {% else %}
              <a href="{% url 'article_list' %}"  role="button" class="btn btn-outline-primary">All News</a>
              {% endif %}
          </div>
        </div>
        <p></p>
        <div class="card">
            <div class="card-header">Comments</div>
            {%  for comment in article.comments.all %}
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p>{{  comment }}</p>
                        <footer class="blockquote-footer">{{  comment.author }}</footer>
                    </blockquote>
                </div>
            {% endfor %}
        </div>
    </div>

<div class="container-fluid my-5">

<!-- ... -->

 <!-- List of comments -->
  {% if comments %}
  <div class="row mt-5">
    <div class="col-lg-6 offset-lg-3">
      Comment{{ comments.count|pluralize }}
      <span class="badge badge-dark ml-2">{{ comments.count }}</span>
    </div>
    {% for comment in comments %}
    <div class="col-lg-6 offset-lg-3 mt-2">
      <div class="card p-2">
        <div class="row">
          <div class="col-12">
            <img class="rounded-circle mr-2" src="{{ object.picture.url }}" width="30px" height="30px" alt="Avatar">
            <strong>{{ comment.name }}</strong> said
          </div>
          <div class="col-12">
            <p class="m-1 mt-3">{{ comment.content }}</p>
            <p class="text-right text-muted"><small>{{ comment.created }}</small></p>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endif %}

  <!-- Form to leave comment -->
  <div class="row mt-5">
    <div class="col-lg-6 offset-lg-3">
      <h3>Leave a comment</h3>
      <form method='POST'>
        {% csrf_token %}
        <div class="form-group">
          <span class="ml-2"></span>{{ form.name.label_tag }}
          <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}" id="id_name"
            name="name" value="{{ form.name.value|default:'' }}">
        </div>
        <div class="form-group">
          <span class="ml-2"></span>
          {{ form.email.label_tag }}
          <span class="text-muted"><small>(Your email address will not be published)</small></span>
          <input type="text" class="form-control {% if form.email.errors %}is-invalid{% endif %}" id="id_email"
            name="email" value="{{ form.email.value|default:'' }}">
        </div>
        <div class="form-group">
          <span class="ml-2"></span>{{ form.content.label_tag }}
          <textarea class="form-control {% if form.content.errors %}is-invalid{% endif %}" id="id_content"
            name="content" rows="4">{{ form.content.value|default:'' }}</textarea>
        </div>
        <button class="btn btn-primary ml-2" type="submit">Submit</button>
      </form>
    </div>
  </div>

</div>
{% endblock content %}

templates/article_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}

    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Submit</button>
    <a class="btn btn-outline-primary" href="{% url 'article_list' %}" role="button">Home</a>
</form>
{% endblock content %}

templates/article_list.html
{% extends 'base.html' %}

{% block title %}Posts{% endblock title %}

{% block content %}
{#    <div class="card-group">#}
    {% for article in object_list %}
        <div class="card" style="width: 50rem;">
            <div class="card-header">
                <span class="font-weight-bold"><a href="{% url 'article_detail' article.pk  %}"><h2>{{ article.title }}</h2></a></span>
            </div>
            {% if article.picture %}z
                <img class="card-img-top" src="{{ article.picture.url }}" alt="{{ article.title }}">
            {%  endif %}
            <div class="card-body">
                {{ article.summary }}...<a href="{% url 'article_detail' article.pk  %}">more</a>
            </div>
            <div class="card-footer text-left text-muted">
                <span class="text-muted">muallif {{ article.author | title }} &middot; {{ article.date }}</span>
            </div>
{#        </div>#}
        <br />
    {% endfor %}
    </div>
{% endblock content %}

templates/article_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data" >
     {% csrf_token %}

    {{ form.media }}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Submit</button>
    <a class="btn btn-outline-primary" href="{% url 'article_list' %}" role="button">Home</a>


</form>
{% endblock content %}

templates/base.html
    {% load static %}

{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.png' %}">
    <meta charset="utf-8">
        <title>{% block title %} Fast News {% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-light " style="background-color: #18E480;">
            <a class="navbar-brand" href="{% url 'home' %}">
              <img src="{% static 'images/logo2.png' %}" alt="" width="200" height="60" class="d-inline-block align-text-top">
            </a>

         <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if user.is_authenticated %}

<!--                <div>-->
<!--                    <a href="{% url 'article_list' %}">Postlarni ko'rish</a>-->
<!--                </div>-->
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link dropdown-toggle" href="#"
                                id="navbarDropdown" role="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                {{ user.username | title }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-lg-right"
                                aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'article_new' %}">New post</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                            </div>
                        </li>
                    </ul>
                {% else %}
                    <form class="form-inline ml-auto">
                        <a href="{% url 'login' %}" class="btn btn-outline-light">Log in</a>
                        <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign Up</a>
                    </form>
                {% endif %}
            </div>
        </nav>

        <main>
            <div class="container">
                {% block content %}
                {% endblock content %}
            </div>
        </main>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

    {% block title %} Homepage {% endblock title %}
{% block content %}
    {% if user.is_authenticated %}
        {{ user.first_name }} {{ user.last_name }}
        <a href="{% url 'logout' %} "button" class="btn btn-outline-primary" ">Logout</a>
<br>
                                 <a href="{% url 'article_list' %}" role="button" class="btn btn-outline-primary">View Last News</a>
    {% else %}
        <h2 align="center">You haven't logged in!</h2>
    <center>
        <a href="{% url 'signup' %}" align="center" class="btn btn-primary">Sign Up </a> <br><br>
        <a href="{% url 'login' %}" align="center" class="btn btn-primary" >Log in</a>
    </center>
    {% endif %}
{% endblock content %}